# Change these first
owner: RadioStatsLTD # Your GitHub organization or username, where this repository lives
repo: status.radiostats.info # The name of this repository

sites:
  - name: RadioStats - Website
    url: https://radiostats.info
    maxResponseTime: 5000
  - name: RadioStats - API
    url: https://api.radiostats.info
    maxResponseTime: 5000

status-website:
  theme: dark
  favicon: https://cdn.radiostats.info/transparent.png
  cname: status.radiostats.info
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.radiostats.info/transparent.png
  name: RadioStats
  introTitle: "**RadioStats** RadioStats is a cutting-edge online platform designed to provide comprehensive statistics and analytics for radio stations."
  introMessage: This is the official RadioStats Status Page
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://radiostats.info
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Discord
      href: https://discord.gg/RadioStats
